"use client";

import type { FormEvent, ReactNode } from "react";
import { useEffect, useState } from "react";
import { CheckCircle2, Loader2, Send } from "lucide-react";
import { Button, GlassCard } from "@/components/ui/heyy";
import HeyySelect from "@/components/ui/heyy-select";
import { useAuth } from "@/components/auth-provider";

export default function ContactForm(){const {user}=useAuth();const [name,setName]=useState("");const [email,setEmail]=useState("");const [topic,setTopic]=useState("General question");const [message,setMessage]=useState("");const [loading,setLoading]=useState(false);const [sent,setSent]=useState(false);const [error,setError]=useState("");useEffect(()=>{if(user){setName(user.user_metadata?.full_name||user.user_metadata?.name||"");setEmail(user.email||"");}const params=new URLSearchParams(window.location.search);const requested=params.get("topic");const position=params.get("position");if(requested==="expert-production")setTopic("Expert production");else if(requested==="career")setTopic("Careers");if(position)setMessage(`I would like to apply for ${position}.\n\n`);},[user]);async function submit(event:FormEvent){event.preventDefault();setLoading(true);setError("");try{const response=await fetch("/api/public/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,email,topic,message,userId:user?.id||null})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Message could not be sent.");setSent(true);}catch(submitError){setError(submitError instanceof Error?submitError.message:"Message could not be sent.");}finally{setLoading(false);}}if(sent)return <GlassCard className="mx-auto max-w-2xl p-9 text-center"><CheckCircle2 size={34} className="mx-auto text-[var(--green)]"/><h2 className="mt-4 text-3xl font-black">Message received</h2><p className="mt-3 text-sm font-semibold leading-7 text-[var(--text-secondary)]">Heyy Studio will review the request and reply to {email}.</p></GlassCard>;return <GlassCard className="mx-auto max-w-3xl p-6 sm:p-8"><form onSubmit={submit} className="grid gap-5 sm:grid-cols-2"><Field label="Name"><input className="heyy-form-field" value={name} onChange={e=>setName(e.target.value)} required/></Field><Field label="Email"><input type="email" className="heyy-form-field" value={email} onChange={e=>setEmail(e.target.value)} required/></Field><div className="sm:col-span-2"><Field label="Topic"><HeyySelect value={topic} ariaLabel="Contact topic" options={["General question","Expert production","Billing & credits","Technical support","Partnership","Careers","Privacy or security"]} onChange={setTopic}/></Field></div><div className="sm:col-span-2"><Field label="Message"><textarea className="heyy-form-field resize-y" rows={7} value={message} onChange={e=>setMessage(e.target.value)} required placeholder="Tell us what you need and include the relevant project context."/></Field></div>{error&&<p className="sm:col-span-2 text-sm font-bold text-red-600 dark:text-red-300">{error}</p>}<div className="sm:col-span-2"><Button type="submit" size="lg" disabled={loading}>{loading?<Loader2 size={16} className="animate-spin"/>:<Send size={16}/>} Send message</Button></div></form></GlassCard>;}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block"><span className="mb-2 block text-[.64rem] font-black uppercase tracking-[.14em] text-[var(--text-secondary)]">{label}</span>{children}</label>;}
