"use client";

import type { ReactNode } from "react";
import { useMemo, useState } from "react";
import { AlertCircle, Download, Loader2, Presentation, Sparkles } from "lucide-react";
import { createSupabaseBrowserClient } from "@/lib/supabase";
import { useAuth } from "@/components/auth-provider";
import { Button, CreditPill, Eyebrow, GlassCard, cx } from "@/components/ui/heyy";
import HeyySelect from "@/components/ui/heyy-select";
import { CREDIT_COSTS } from "@/lib/credits/config";

type Slide = { title: string; subtitle?: string; bullets?: string[]; speakerNotes?: string };
type Result = { fileUrl: string; asset?: { id: string }; slides: Slide[]; creditsUsed: number };

export default function PowerPointWorkbench(){
  const supabase=useMemo(()=>createSupabaseBrowserClient(),[]); const {refreshAccount}=useAuth();
  const [title,setTitle]=useState(""); const [audience,setAudience]=useState(""); const [objective,setObjective]=useState(""); const [source,setSource]=useState(""); const [slides,setSlides]=useState(10); const [tone,setTone]=useState("Premium and concise"); const [mode,setMode]=useState<"draft"|"full">("full"); const [result,setResult]=useState<Result|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
  const cost=mode==="full"?CREDIT_COSTS.powerpointFull:CREDIT_COSTS.powerpointDraft;
  async function generate(){if(!title.trim()||!objective.trim()||source.trim().length<30){setError("Add a title, objective and enough source content to build the presentation.");return;}setLoading(true);setError("");try{const {data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error("Your session expired. Sign in again.");const response=await fetch("/api/tools/powerpoint-generator/generate",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({title,audience,objective,source,slideCount:slides,tone,mode})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Presentation generation failed.");setResult(payload);await refreshAccount();}catch(generationError){setError(generationError instanceof Error?generationError.message:"Presentation generation failed.");}finally{setLoading(false);}}
  return <div className="grid gap-5 xl:grid-cols-[.78fr_1.22fr]">
    <GlassCard className="p-5 sm:p-6"><Eyebrow>Brief & structure</Eyebrow><h2 className="mt-3 text-2xl font-black tracking-[-.045em]">Build an editable deck</h2>
      <div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Presentation title"><input className="heyy-form-field" value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Heyy Studio investor overview"/></Field><Field label="Audience"><input className="heyy-form-field" value={audience} onChange={e=>setAudience(e.target.value)} placeholder="Clients, investors, internal team..."/></Field></div>
      <div className="mt-5"><Field label="Objective"><textarea className="heyy-form-field resize-y" rows={3} value={objective} onChange={e=>setObjective(e.target.value)} placeholder="What should the audience understand, decide or do?"/></Field></div>
      <div className="mt-5"><Field label="Source content"><textarea className="heyy-form-field resize-y" rows={9} value={source} onChange={e=>setSource(e.target.value)} placeholder="Paste the brief, proposal, notes, report or source material. The generator will organize it into a clear story."/></Field></div>
      <div className="mt-5 grid gap-5 sm:grid-cols-2"><Field label="Number of slides"><input type="number" min={5} max={20} className="heyy-form-field" value={slides} onChange={e=>setSlides(Math.max(5,Math.min(20,Number(e.target.value)||10)))}/></Field><Field label="Tone"><HeyySelect value={tone} tone="interior" ariaLabel="Presentation tone" options={["Premium and concise","Corporate and analytical","Bold and persuasive","Warm and explanatory","Minimal and visual"]} onChange={setTone}/></Field></div>
      <div className="mt-5"><label className="text-[.64rem] font-black uppercase tracking-[.14em] text-[var(--text-secondary)]">Generation mode</label><div className="mt-2 grid grid-cols-2 gap-2">{(["draft","full"] as const).map(item=><button key={item} onClick={()=>setMode(item)} className={cx("min-h-12 rounded-2xl border text-xs font-black capitalize transition",mode===item?"border-[var(--accent)] bg-[var(--accent)] text-white":"border-[var(--border-strong)] bg-[var(--surface)] hover:border-[var(--accent)]")}>{item}<span className="ml-1 opacity-70">· {item==="full"?CREDIT_COSTS.powerpointFull:CREDIT_COSTS.powerpointDraft}</span></button>)}</div></div>
      {error&&<div className="mt-5 flex gap-3 rounded-2xl border border-red-300/60 bg-red-500/10 p-4 text-sm font-bold text-red-700 dark:text-red-200"><AlertCircle size={18} className="shrink-0"/>{error}</div>}
      <Button className="mt-6 w-full" size="lg" onClick={()=>void generate()} disabled={loading}>{loading?<Loader2 size={16} className="animate-spin"/>:<Sparkles size={16}/>} {loading?"Writing and designing slides…":`Generate PowerPoint · ${cost} credits`}</Button>
    </GlassCard>
    <GlassCard className="min-h-[680px] p-5 sm:p-6"><div className="flex items-center justify-between gap-4"><div><Eyebrow>Presentation preview</Eyebrow><h2 className="mt-2 text-2xl font-black tracking-[-.045em]">Story outline</h2></div><CreditPill credits={result?.creditsUsed||cost}/></div>
      {loading?<div className="grid min-h-[560px] place-items-center"><div className="text-center"><Loader2 size={34} className="mx-auto animate-spin text-[var(--accent-strong)]"/><h3 className="mt-4 text-xl font-black">Structuring the deck</h3><p className="mt-2 text-sm font-semibold text-[var(--text-muted)]">Creating narrative flow, slide content and an editable layout.</p></div></div>:result?<><div className="mt-6 grid gap-3 sm:grid-cols-2">{result.slides.map((slide,index)=><div key={`${index}-${slide.title}`} className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-4"><div className="flex items-start gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-xl bg-orange-500/12 text-[.65rem] font-black text-orange-600">{String(index+1).padStart(2,"0")}</span><div><p className="text-sm font-black">{slide.title}</p>{slide.subtitle&&<p className="mt-1 text-[.68rem] font-semibold text-[var(--text-muted)]">{slide.subtitle}</p>}</div></div>{slide.bullets&&<ul className="mt-3 space-y-1.5 pl-11">{slide.bullets.slice(0,3).map((bullet,itemIndex)=><li key={itemIndex} className="text-[.68rem] font-semibold leading-5 text-[var(--text-secondary)]">• {bullet}</li>)}</ul>}</div>)}</div><a href={result.fileUrl} target="_blank" rel="noreferrer" className="heyy-button mt-6 inline-flex min-h-11 items-center justify-center gap-2 rounded-full bg-[var(--button-primary)] px-5 text-sm font-extrabold text-[var(--button-primary-text)]"><Download size={15}/> Download editable .pptx</a></>:<div className="grid min-h-[560px] place-items-center"><div className="max-w-sm text-center"><Presentation size={38} className="mx-auto text-orange-500"/><h3 className="mt-4 text-xl font-black">Your deck outline will appear here</h3><p className="mt-2 text-sm font-semibold leading-6 text-[var(--text-secondary)]">The PowerPoint is built as a native editable file, not a flattened image export.</p></div></div>}
    </GlassCard>
  </div>;
}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block"><span className="mb-2 block text-[.64rem] font-black uppercase tracking-[.14em] text-[var(--text-secondary)]">{label}</span>{children}</label>;}
