"use client";

import { useEffect, useMemo, useState } from "react";
import { LoaderCircle, Megaphone, Pencil, Plus, Send, X } from "lucide-react";

type Announcement={id:string;title:string;subject:string;preheader?:string|null;body:string;cta_label?:string|null;cta_path?:string|null;audience:string;channel:string;status:string;sent_count:number;failed_count:number;created_at:string};
type Form={title:string;subject:string;preheader:string;body:string;ctaLabel:string;ctaPath:string;audience:string;channel:string};
const empty:Form={title:"",subject:"",preheader:"",body:"",ctaLabel:"Open Heyy Studio",ctaPath:"/dashboard",audience:"everyone",channel:"both"};

export default function AnnouncementsManager(){
  const[rows,setRows]=useState<Announcement[]>([]);const[loading,setLoading]=useState(true);const[editing,setEditing]=useState<Announcement|"new"|null>(null);const[form,setForm]=useState<Form>(empty);const[message,setMessage]=useState("");const[sending,setSending]=useState("");
  const drafts=useMemo(()=>rows.filter(row=>row.status==="draft"),[rows]);
  async function load(){setLoading(true);const r=await fetch("/api/admin/communications/announcements",{cache:"no-store"});const d=await r.json();setRows(d.announcements||[]);setLoading(false);}
  useEffect(()=>{void load();},[]);
  function open(row:Announcement|"new"){setEditing(row);setMessage("");if(row==="new"){setForm(empty);return;}setForm({title:row.title,subject:row.subject,preheader:row.preheader||"",body:row.body,ctaLabel:row.cta_label||"Open Heyy Studio",ctaPath:row.cta_path||"/dashboard",audience:row.audience,channel:row.channel});}
  async function save(){const payload={...form,cta_label:form.ctaLabel,cta_path:form.ctaPath,...(editing!=="new"&&editing?{id:editing.id}:{})};const r=await fetch("/api/admin/communications/announcements",{method:editing==="new"?"POST":"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok){setMessage(d.error||"Announcement could not be saved.");return;}setEditing(null);setForm(empty);setMessage("Announcement saved as draft.");await load();}
  async function send(row:Announcement){if(!confirm(`Send “${row.title}” now? This cannot be unsent.`))return;setSending(row.id);setMessage("");const r=await fetch("/api/admin/communications/announcements/send",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:row.id})});const d=await r.json();setSending("");setMessage(r.ok?`Announcement sent. ${d.result?.sentCount||0} deliveries recorded${d.result?.failedCount?`, ${d.result.failedCount} failed`:""}.`:d.error||"Announcement could not be sent.");await load();}
  return <section className="rounded-3xl border border-violet-100 bg-white p-6 shadow-sm">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-violet-600"><Megaphone size={17}/><p className="text-[.62rem] font-black uppercase tracking-[.16em]">Announcements</p></div><h2 className="mt-2 text-2xl font-black">Email and in-app broadcasts</h2><p className="mt-2 max-w-3xl text-sm font-semibold leading-6 text-slate-500">Target Free, Starter, Pro, all subscribers or everyone. Marketing emails only go to users who opted in; in-app announcements can reach the selected product audience.</p></div><button onClick={()=>open("new")} className="inline-flex items-center gap-2 rounded-full bg-slate-950 px-5 py-3 text-xs font-black text-white"><Plus size={14}/>New announcement</button></div>
    {message&&<p className="mt-4 rounded-2xl bg-slate-50 px-4 py-3 text-xs font-bold text-slate-600">{message}</p>}
    {loading?<div className="grid min-h-36 place-items-center"><LoaderCircle className="animate-spin text-violet-600"/></div>:rows.length===0?<p className="mt-6 text-sm font-semibold text-slate-400">No announcements yet.</p>:<div className="mt-6 divide-y divide-slate-100">{rows.map(row=><div key={row.id} className="flex flex-wrap items-center justify-between gap-4 py-4"><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-black">{row.title}</p><span className={`rounded-full px-2 py-1 text-[.62rem] font-black uppercase ${row.status==="sent"?"bg-emerald-50 text-emerald-700":row.status==="failed"?"bg-red-50 text-red-600":"bg-violet-50 text-violet-700"}`}>{row.status}</span></div><p className="mt-1 text-xs font-semibold text-slate-400">{row.audience} · {row.channel} · {new Date(row.created_at).toLocaleString()}</p>{row.status==="sent"&&<p className="mt-1 text-[.68rem] font-bold text-slate-400">{row.sent_count} deliveries · {row.failed_count} failed</p>}</div><div className="flex gap-2">{row.status==="draft"&&<button onClick={()=>open(row)} className="grid h-9 w-9 place-items-center rounded-full border border-violet-100 text-violet-600"><Pencil size={14}/></button>}{row.status==="draft"&&<button disabled={sending===row.id} onClick={()=>void send(row)} className="inline-flex items-center gap-2 rounded-full bg-violet-600 px-4 py-2 text-xs font-black text-white disabled:opacity-50">{sending===row.id?<LoaderCircle size={14} className="animate-spin"/>:<Send size={14}/>}Send now</button>}</div></div>)}</div>}
    {editing&&<div className="fixed inset-0 z-[150] grid place-items-center overflow-y-auto bg-slate-950/45 p-4 backdrop-blur-sm"><div className="my-8 w-full max-w-3xl rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-[.62rem] font-black uppercase tracking-[.16em] text-violet-600">Announcement draft</p><h3 className="mt-2 text-3xl font-black">Compose update</h3></div><button onClick={()=>setEditing(null)} className="grid h-10 w-10 place-items-center rounded-full border border-slate-200"><X size={16}/></button></div><div className="mt-6 grid gap-4 md:grid-cols-2"><Field label="Title" value={form.title} onChange={v=>setForm({...form,title:v})}/><Field label="Email subject" value={form.subject} onChange={v=>setForm({...form,subject:v})}/><Field label="Preheader" value={form.preheader} onChange={v=>setForm({...form,preheader:v})}/><Field label="Button label" value={form.ctaLabel} onChange={v=>setForm({...form,ctaLabel:v})}/><div className="md:col-span-2"><Field label="Message" value={form.body} onChange={v=>setForm({...form,body:v})} multiline/></div><Field label="Button path" value={form.ctaPath} onChange={v=>setForm({...form,ctaPath:v})} placeholder="/dashboard"/><label><span className="mb-2 block text-[.62rem] font-black uppercase tracking-[.14em] text-slate-500">Audience</span><select value={form.audience} onChange={e=>setForm({...form,audience:e.target.value})} className="w-full rounded-2xl border border-slate-200 px-4 py-3 text-sm font-bold"><option value="everyone">Everyone</option><option value="free">Free</option><option value="starter">Starter</option><option value="pro">Pro</option><option value="subscribers">All subscribers</option></select></label><label><span className="mb-2 block text-[.62rem] font-black uppercase tracking-[.14em] text-slate-500">Channels</span><select value={form.channel} onChange={e=>setForm({...form,channel:e.target.value})} className="w-full rounded-2xl border border-slate-200 px-4 py-3 text-sm font-bold"><option value="both">Email + in-app</option><option value="email">Email only</option><option value="in_app">In-app only</option></select></label></div><p className="mt-4 text-xs font-semibold leading-5 text-slate-500">Use a relative button path such as <code>/dashboard</code> or <code>/tools</code>. The Beta or live hostname is added automatically from the central site URL. You can use <code>{"{{first_name}}"}</code> in the subject/message.</p><div className="mt-6 flex gap-2"><button onClick={()=>void save()} className="rounded-full bg-slate-950 px-5 py-3 text-xs font-black text-white">Save draft</button><button onClick={()=>setEditing(null)} className="rounded-full border border-slate-200 px-5 py-3 text-xs font-black">Cancel</button></div></div></div>}
  </section>;
}
function Field({label,value,onChange,placeholder="",multiline=false}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string;multiline?:boolean}){return <label><span className="mb-2 block text-[.62rem] font-black uppercase tracking-[.14em] text-slate-500">{label}</span>{multiline?<textarea rows={6} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="w-full rounded-2xl border border-slate-200 px-4 py-3 text-sm font-semibold outline-none focus:border-violet-400"/>:<input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="w-full rounded-2xl border border-slate-200 px-4 py-3 text-sm font-bold outline-none focus:border-violet-400"/>}</label>}
