function getSection(text: string, title: string) {
  const clean = text
    .replace("📋 PROJECT BRIEF", "")
    .replace("PROJECT BRIEF", "")
    .trim();

  const headings = [
    "PROJECT OVERVIEW",
    "PROJECT OBJECTIVES",
    "TARGET AUDIENCE / USERS",
    "CREATIVE DIRECTION",
    "RECOMMENDED SCOPE",
    "KEY CONSIDERATIONS",
    "RECOMMENDED NEXT STEPS",
    "EXPERT RECOMMENDATION",
    "HEYY STUDIO NOTES",
  ];

  const start = clean.indexOf(title);
  if (start === -1) return "";

  const afterTitle = clean.slice(start + title.length);
  let end = afterTitle.length;

  for (const heading of headings) {
    if (heading === title) continue;

    const index = afterTitle.indexOf(heading);
    if (index !== -1 && index < end) end = index;
  }

  return afterTitle.slice(0, end).trim();
}

function Section({
  number,
  title,
  children,
}: {
  number: string;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="border-t border-white/10 py-7">
      <div className="mb-4 flex items-center gap-4">
        <span className="text-xs font-bold tracking-[0.25em] text-[#A78BFA]">
          {number}
        </span>

        <h3 className="text-xs font-bold uppercase tracking-[0.25em] text-white/70">
          {title}
        </h3>
      </div>

      <div className="whitespace-pre-line text-[15px] leading-8 text-white/82">
        {children}
      </div>
    </div>
  );
}

export default function BriefCard({ text }: { text: string }) {
  const overview = getSection(text, "PROJECT OVERVIEW");
  const objectives = getSection(text, "PROJECT OBJECTIVES");
  const audience = getSection(text, "TARGET AUDIENCE / USERS");
  const direction = getSection(text, "CREATIVE DIRECTION");
  const scope = getSection(text, "RECOMMENDED SCOPE");
  const considerations = getSection(text, "KEY CONSIDERATIONS");
  const nextSteps = getSection(text, "RECOMMENDED NEXT STEPS");
  const expert = getSection(text, "EXPERT RECOMMENDATION");
  const notes = getSection(text, "HEYY STUDIO NOTES");

  return (
    <div className="w-full rounded-[32px] border border-white/10 bg-[#151020] p-8 text-left shadow-2xl shadow-black/40 md:p-10">
      <div className="pb-8">
        <p className="text-xs uppercase tracking-[0.35em] text-white/35">
          Generated by Heyy Studio AI
        </p>

        <h2 className="mt-3 text-3xl font-semibold text-white">
          Project Brief
        </h2>
      </div>

      {overview && (
        <Section number="01" title="Project Overview">
          {overview}
        </Section>
      )}

      {objectives && (
        <Section number="02" title="Objectives">
          {objectives}
        </Section>
      )}

      {audience && (
        <Section number="03" title="Audience / Users">
          {audience}
        </Section>
      )}

      {direction && (
        <Section number="04" title="Creative Direction">
          {direction}
        </Section>
      )}

      {scope && (
        <Section number="05" title="Recommended Scope">
          {scope}
        </Section>
      )}

      {considerations && (
        <Section number="06" title="Key Considerations">
          {considerations}
        </Section>
      )}

      {nextSteps && (
        <Section number="07" title="Recommended Next Steps">
          {nextSteps}
        </Section>
      )}

      {expert && (
        <div className="mt-4 rounded-2xl border border-[#8B5CF6]/25 bg-[#8B5CF6]/10 p-6">
          <p className="mb-3 text-xs font-bold uppercase tracking-[0.25em] text-[#C4B5FD]">
            Expert Recommendation
          </p>

          <p className="text-[15px] leading-8 text-white/85">
            {expert}
          </p>
        </div>
      )}

      {notes && (
        <p className="mt-6 border-t border-white/10 pt-5 text-sm leading-7 text-white/45">
          {notes}
        </p>
      )}
    </div>
  );
}