export type ArchitectureMaterialLibraryItem = {
  key: string;
  name: string;
  image: string;
  category: string;
  finish: string;
  application: string;
  cost: string;
  maintenance: string;
  climate: string;
  sustainability: string;
  tags: string[];
};

export const ARCHITECTURE_MATERIAL_LIBRARY: ArchitectureMaterialLibraryItem[] = [
  { key: "warm-limestone", name: "Warm Limestone", image: "/architecture/materials/warm-limestone.jpg", category: "Stone", finish: "Honed", application: "Primary façade, entry walls and landscape edges", cost: "Premium", maintenance: "Low", climate: "Strong in warm and dry climates when detailed and sealed correctly", sustainability: "Prefer local or responsibly sourced stone", tags: ["stone", "beige", "facade", "warm", "luxury"] },
  { key: "travertine", name: "Travertine", image: "/architecture/materials/travertine.jpg", category: "Stone", finish: "Vein cut", application: "Feature façade, arrival walls and terraces", cost: "Premium", maintenance: "Medium", climate: "Seal and detail for exposure and freeze-thaw conditions", sustainability: "Confirm quarry source and transport impact", tags: ["stone", "cream", "feature", "facade"] },
  { key: "granite", name: "Granite", image: "/architecture/materials/extra/granite.svg", category: "Stone", finish: "Flamed or honed", application: "Plinths, paving, steps and durable external walls", cost: "High", maintenance: "Low", climate: "Durable across most climates when joints and slip resistance are resolved", sustainability: "Prefer regional stone and efficient module sizes", tags: ["stone", "grey", "durable", "paving"] },
  { key: "basalt", name: "Basalt", image: "/architecture/materials/extra/basalt.svg", category: "Stone", finish: "Honed", application: "Dark plinths, landscape walls and feature masses", cost: "High", maintenance: "Low", climate: "Good weather resistance; confirm heat gain in exposed sunny locations", sustainability: "Specify local or recycled-content alternatives where available", tags: ["stone", "dark", "black", "feature"] },
  { key: "sandstone", name: "Sandstone", image: "/architecture/materials/extra/sandstone.svg", category: "Stone", finish: "Sawn or honed", application: "Façade walls, garden walls and shaded terraces", cost: "Medium to high", maintenance: "Medium", climate: "Select density and sealing for local moisture and salt exposure", sustainability: "Local sourcing can reduce transport impact", tags: ["stone", "sand", "natural", "facade"] },
  { key: "board-formed-concrete", name: "Board-Formed Concrete", image: "/architecture/materials/board-formed-concrete.jpg", category: "Concrete & Earth", finish: "Textured", application: "Feature massing, retaining walls and soffits", cost: "High", maintenance: "Low", climate: "Durable with correct concrete cover, waterproofing and joints", sustainability: "Use lower-carbon mixes and efficient structural design", tags: ["concrete", "brutalist", "texture", "structure"] },
  { key: "rammed-earth", name: "Rammed Earth", image: "/architecture/materials/extra/rammed-earth.svg", category: "Concrete & Earth", finish: "Natural layered", application: "Feature walls, thermal-mass zones and sheltered façades", cost: "High", maintenance: "Medium", climate: "Best with protected caps, bases and rain detailing", sustainability: "Can use local soil and low-processing construction methods", tags: ["earth", "natural", "sustainable", "warm"] },
  { key: "exposed-aggregate", name: "Exposed Aggregate Concrete", image: "/architecture/materials/extra/exposed-aggregate.svg", category: "Concrete & Earth", finish: "Washed aggregate", application: "Driveways, paths, terraces and external steps", cost: "Medium", maintenance: "Low", climate: "Confirm slip resistance and movement joints", sustainability: "Use recycled aggregate and lower-carbon cement blends where possible", tags: ["concrete", "paving", "outdoor", "aggregate"] },
  { key: "gfrc-panel", name: "GFRC / GRC Panel", image: "/architecture/materials/extra/gfrc-panel.svg", category: "Concrete & Earth", finish: "Smooth or textured", application: "Lightweight façade panels, fins and moulded details", cost: "High", maintenance: "Low to medium", climate: "Detail fixings, joints and water management for local exposure", sustainability: "Optimise panel thickness and recycled content", tags: ["gfrc", "grc", "panel", "facade", "moulded"] },
  { key: "terracotta-brick", name: "Terracotta Brick", image: "/architecture/materials/terracotta-brick.jpg", category: "Brick & Terracotta", finish: "Natural", application: "Main walls, screened layers and landscape walls", cost: "Medium", maintenance: "Low", climate: "Good thermal mass; verify cavity and moisture details", sustainability: "Choose local manufacturing and durable mortar systems", tags: ["brick", "terracotta", "red", "warm"] },
  { key: "exposed-brick", name: "Exposed Brick", image: "/architecture/materials/extra/exposed-brick.svg", category: "Brick & Terracotta", finish: "Tumbled or smooth", application: "Primary walls, courtyards and internal-external continuity", cost: "Medium", maintenance: "Low", climate: "Use suitable brick class, cavity and flashing for exposure", sustainability: "Reclaimed brick can reduce embodied impact", tags: ["brick", "masonry", "red", "industrial"] },
  { key: "terracotta-screen", name: "Terracotta Screen", image: "/architecture/materials/extra/terracotta-screen.svg", category: "Brick & Terracotta", finish: "Natural fired", application: "Shading screens, privacy walls and ventilated façades", cost: "High", maintenance: "Low", climate: "Good for shaded ventilation; engineer fixings and wind loads", sustainability: "Long-life modular clay units with low maintenance", tags: ["terracotta", "screen", "shade", "privacy"] },
  { key: "ceramic-facade-tile", name: "Ceramic Façade Tile", image: "/architecture/materials/extra/ceramic-facade-tile.svg", category: "Brick & Terracotta", finish: "Matte", application: "Ventilated façades, feature bands and soffit accents", cost: "Medium to high", maintenance: "Low", climate: "Select tested façade systems and corrosion-resistant fixings", sustainability: "Durable modular finish; assess firing and transport impacts", tags: ["ceramic", "tile", "facade", "colour"] },
  { key: "mineral-render", name: "Mineral Render", image: "/architecture/materials/mineral-render.jpg", category: "Render & Coatings", finish: "Fine texture", application: "Secondary walls and monolithic volumes", cost: "Controlled", maintenance: "Medium", climate: "Select a system for local moisture and temperature ranges", sustainability: "Mineral systems can reduce synthetic coating use", tags: ["render", "stucco", "white", "minimal"] },
  { key: "corten-steel", name: "Corten Steel", image: "/architecture/materials/extra/corten-steel.svg", category: "Metal", finish: "Weathered", application: "Feature cladding, screens, landscape walls and gates", cost: "High", maintenance: "Low", climate: "Manage runoff staining and avoid unsuitable marine exposure", sustainability: "Long-life recyclable steel; minimise unnecessary thickness", tags: ["steel", "rust", "corten", "feature"] },
  { key: "zinc-panel", name: "Zinc Panel", image: "/architecture/materials/extra/zinc-panel.svg", category: "Metal", finish: "Pre-weathered", application: "Roof and ventilated wall cladding", cost: "Premium", maintenance: "Low", climate: "Detail ventilation, compatibility and coastal conditions", sustainability: "Highly recyclable and long-life when detailed correctly", tags: ["zinc", "metal", "roof", "cladding"] },
  { key: "copper-panel", name: "Copper Panel", image: "/architecture/materials/extra/copper-panel.svg", category: "Metal", finish: "Natural or pre-patinated", application: "Feature roofs, façades and entry details", cost: "Premium", maintenance: "Low", climate: "Accept natural patina and manage runoff compatibility", sustainability: "High recycled content and recyclability are possible", tags: ["copper", "metal", "patina", "premium"] },
  { key: "bronze-metal", name: "Bronze Metal", image: "/architecture/materials/bronze-metal.jpg", category: "Metal", finish: "Brushed", application: "Entry, gates, screens and feature trims", cost: "Premium", maintenance: "Low to medium", climate: "Patina and corrosion behaviour must be accepted", sustainability: "Specify recycled content and replaceable components", tags: ["bronze", "metal", "luxury", "detail"] },
  { key: "perforated-metal", name: "Perforated Metal", image: "/architecture/materials/extra/perforated-metal.svg", category: "Metal", finish: "Powder coated", application: "Solar screens, plant enclosures and ventilated façades", cost: "Medium to high", maintenance: "Low", climate: "Specify corrosion class, open area and wind-load performance", sustainability: "Lightweight recyclable screen system", tags: ["metal", "screen", "perforated", "shade"] },
  { key: "black-aluminium", name: "Black Aluminium", image: "/architecture/materials/black-aluminium.jpg", category: "Windows & Frames", finish: "Powder coated", application: "Window, door and screen frames", cost: "Medium", maintenance: "Low", climate: "Specify thermal breaks and coastal-grade coating where required", sustainability: "Prioritise recycled aluminium and durable finishes", tags: ["aluminium", "black", "windows", "frames"] },
  { key: "white-aluminium", name: "White Aluminium", image: "/architecture/materials/extra/white-aluminium.svg", category: "Windows & Frames", finish: "Powder coated", application: "Light window systems, doors and minimal frames", cost: "Medium", maintenance: "Low", climate: "Use thermal breaks and exposure-appropriate coating systems", sustainability: "High recycled content and recyclability are possible", tags: ["aluminium", "white", "windows", "frames"] },
  { key: "anodized-bronze", name: "Anodized Bronze Aluminium", image: "/architecture/materials/extra/anodized-bronze.svg", category: "Windows & Frames", finish: "Anodized", application: "Premium window frames, fins and façade trims", cost: "High", maintenance: "Low", climate: "Confirm anodizing grade and colour stability for exposure", sustainability: "Durable recyclable aluminium system", tags: ["aluminium", "bronze", "frames", "premium"] },
  { key: "low-iron-glass", name: "Low-Iron Glass", image: "/architecture/materials/low-iron-glass.jpg", category: "Glazing", finish: "Clear", application: "Main openings, view frames and display façades", cost: "High", maintenance: "Medium", climate: "Performance glass and external shading are essential", sustainability: "Reduce excessive glazing and improve thermal performance", tags: ["glass", "clear", "glazing", "views"] },
  { key: "fluted-glass", name: "Fluted Glass", image: "/architecture/materials/extra/fluted-glass.svg", category: "Glazing", finish: "Textured translucent", application: "Privacy glazing, entry screens and internal-external partitions", cost: "Medium to high", maintenance: "Medium", climate: "Use laminated or insulated assemblies where performance requires", sustainability: "Use selectively and detail for long service life", tags: ["glass", "fluted", "privacy", "translucent"] },
  { key: "polycarbonate", name: "Translucent Polycarbonate", image: "/architecture/materials/extra/polycarbonate.svg", category: "Glazing", finish: "Translucent", application: "Lightweight façades, rooflights and service-zone screens", cost: "Controlled to medium", maintenance: "Medium", climate: "Confirm UV stability, fire performance and thermal movement", sustainability: "Specify replaceable recyclable systems and long warranties", tags: ["polycarbonate", "translucent", "lightweight", "rooflight"] },
  { key: "natural-oak", name: "Natural Oak", image: "/architecture/materials/natural-oak.jpg", category: "Timber", finish: "Oiled", application: "Shading, soffits and protected warm details", cost: "High", maintenance: "Medium", climate: "Needs protected detailing and suitable species selection", sustainability: "Specify certified timber", tags: ["timber", "oak", "warm", "soffit"] },
  { key: "charred-timber", name: "Charred Timber", image: "/architecture/materials/charred-timber.jpg", category: "Timber", finish: "Charred", application: "Screens and feature cladding", cost: "High", maintenance: "Medium", climate: "Confirm fire, moisture and UV performance", sustainability: "Use certified durable species", tags: ["timber", "charred", "black", "cladding"] },
  { key: "timber-decking", name: "Timber Decking", image: "/architecture/materials/extra/timber-decking.svg", category: "Timber", finish: "Oiled or weathered", application: "Terraces, pool decks and outdoor walkways", cost: "Medium to high", maintenance: "Medium to high", climate: "Select durable species, drainage and slip-resistant detailing", sustainability: "Specify certified timber or verified recycled composite alternatives", tags: ["timber", "deck", "outdoor", "terrace"] },
  { key: "breeze-block", name: "Breeze Block", image: "/architecture/materials/extra/breeze-block.svg", category: "Screens", finish: "Natural or painted", application: "Privacy walls, ventilated courtyards and shaded edges", cost: "Controlled to medium", maintenance: "Low", climate: "Strong passive-shading option when wind and structure are resolved", sustainability: "Simple modular masonry with long service life", tags: ["screen", "block", "shade", "privacy"] },
  { key: "mashrabiya-screen", name: "Mashrabiya Screen", image: "/architecture/materials/extra/mashrabiya-screen.svg", category: "Screens", finish: "Timber, aluminium or GRC", application: "Solar control, privacy and culturally responsive façades", cost: "High", maintenance: "Material dependent", climate: "Excellent for layered shade; engineer wind, access and cleaning", sustainability: "Optimise pattern density and use durable replaceable modules", tags: ["mashrabiya", "screen", "arabic", "shade"] },
  { key: "standing-seam-metal", name: "Standing-Seam Metal", image: "/architecture/materials/standing-seam-metal.jpg", category: "Roof", finish: "Matte", application: "Roof and selected wall planes", cost: "Medium", maintenance: "Low", climate: "Detail acoustics, condensation and coastal corrosion", sustainability: "Highly recyclable and suitable for long-life assemblies", tags: ["roof", "metal", "standing seam", "cladding"] },
  { key: "clay-roof-tile", name: "Clay Roof Tile", image: "/architecture/materials/extra/clay-roof-tile.svg", category: "Roof", finish: "Natural fired", application: "Pitched roofs and Mediterranean roof forms", cost: "Medium", maintenance: "Low", climate: "Suitable for hot climates; confirm wind fixing and underlay", sustainability: "Long-life natural material with reusable units", tags: ["roof", "clay", "mediterranean", "tile"] },
  { key: "natural-slate", name: "Natural Slate", image: "/architecture/materials/extra/natural-slate.svg", category: "Roof", finish: "Split face", application: "Premium pitched roofs and feature wall planes", cost: "Premium", maintenance: "Low", climate: "Excellent durability; verify fixing system and structural load", sustainability: "Long service life; source responsibly", tags: ["roof", "slate", "dark", "premium"] },
  { key: "green-roof", name: "Green Roof", image: "/architecture/materials/extra/green-roof.svg", category: "Roof", finish: "Extensive planted", application: "Flat roofs, terraces and biodiversity zones", cost: "High", maintenance: "Medium", climate: "Planting, drainage and irrigation must match local climate", sustainability: "Supports biodiversity, stormwater control and thermal buffering", tags: ["roof", "green", "landscape", "sustainable"] },
  { key: "terrazzo", name: "Terrazzo", image: "/architecture/materials/terrazzo.jpg", category: "External Flooring", finish: "Honed", application: "Terraces, entry and wet zones", cost: "High", maintenance: "Low to medium", climate: "Confirm slip resistance and movement joints", sustainability: "Can incorporate recycled aggregate", tags: ["flooring", "terrazzo", "terrace", "entry"] },
  { key: "porcelain-paver", name: "Porcelain Paver", image: "/architecture/materials/extra/porcelain-paver.svg", category: "External Flooring", finish: "Textured", application: "Terraces, pool surrounds and roof decks", cost: "Medium", maintenance: "Low", climate: "Choose slip rating, pedestal system and frost class as required", sustainability: "Durable modular finish; assess firing and transport impacts", tags: ["flooring", "porcelain", "paver", "pool"] },
];

export const ARCHITECTURE_MATERIAL_CATEGORIES = [
  "All",
  ...Array.from(new Set(ARCHITECTURE_MATERIAL_LIBRARY.map((item) => item.category))),
];

export function findArchitectureMaterial(key: string) {
  return ARCHITECTURE_MATERIAL_LIBRARY.find((item) => item.key === key) || null;
}
