export type CommunicationTemplateDefinition = {
  key: string;
  name: string;
  category: "Onboarding" | "Billing" | "Production" | "Careers" | "Announcements";
  description: string;
  defaultSubject?: string;
  defaultPreheader?: string;
  defaultEyebrow?: string;
  defaultTitle?: string;
  defaultBody?: string;
  defaultCtaLabel?: string;
};

export const COMMUNICATION_TEMPLATE_CATALOG: CommunicationTemplateDefinition[] = [
  {
    key: "welcome",
    name: "Welcome email",
    category: "Onboarding",
    description: "Sent once after a new account is verified or first created with Google.",
    defaultSubject: "Welcome to Heyy Studio",
    defaultPreheader: "Your Heyy Studio workspace is ready.",
    defaultEyebrow: "Welcome",
    defaultTitle: "Your creative workspace is ready",
    defaultBody: "Welcome {{first_name}}. Explore Studios, use the creative tools and bring in expert production whenever an idea is ready to become a finished asset.",
    defaultCtaLabel: "Start creating",
  },
  {
    key: "account.goodbye",
    name: "Account deletion goodbye",
    category: "Onboarding",
    description: "Sent after a customer successfully deletes their Heyy Studio account.",
    defaultSubject: "Your Heyy Studio account has been deleted",
    defaultPreheader: "Your Heyy Studio account deletion is complete.",
    defaultEyebrow: "Account deleted",
    defaultTitle: "Thanks for creating with us",
    defaultBody: "Thanks for being part of Heyy Studio, {{first_name}}. Your account has been deleted and access to your workspace has ended. Limited payment or compliance records may be retained where required for billing, tax, fraud-prevention or legal obligations.",
    defaultCtaLabel: "Visit Heyy Studio",
  },
  {
    key: "career.application.received.client",
    name: "Career application received — applicant",
    category: "Careers",
    description: "Sent automatically after a candidate successfully submits a Careers application.",
    defaultSubject: "Application received — {{role_title}}",
    defaultPreheader: "We’ve received your application to Heyy Studio.",
    defaultEyebrow: "Application received",
    defaultTitle: "Thanks for applying to Heyy Studio",
    defaultBody: "Thank you for applying for {{role_title}}, {{first_name}}. We’ve received your application. Our team will review it and we’ll contact you if you’re shortlisted for the next stage.",
    defaultCtaLabel: "View careers",
  },
  {
    key: "career.application.received.admin",
    name: "Career application received — admin",
    category: "Careers",
    description: "Operational notification sent to ADMIN_EMAIL when a new Careers application is received.",
    defaultSubject: "New career application — {{role_title}}",
    defaultPreheader: "A new candidate application is ready for review.",
    defaultEyebrow: "New career application",
    defaultTitle: "A new candidate is ready for review",
    defaultBody: "{{applicant_name}} submitted an application for {{role_title}}. Review the application, CV and candidate links in Admin.",
    defaultCtaLabel: "Review application",
  },
  {
    key: "payment.receipt",
    name: "Payment confirmation + invoice",
    category: "Billing",
    description: "Sent after successful subscription, credit-pack and production payments with a Heyy Studio PDF invoice attached.",
    defaultSubject: "Payment received — {{description}}",
    defaultPreheader: "Your payment was successful and your invoice is attached.",
    defaultEyebrow: "Payment confirmed",
    defaultTitle: "Thanks — your payment is complete",
    defaultBody: "We received your payment for {{description}}. Your Heyy Studio invoice is attached to this email and is also available from Payment history in your account.",
    defaultCtaLabel: "View payment history",
  },
  {
    key: "announcement",
    name: "Product announcement",
    category: "Announcements",
    description: "Reusable marketing/update shell used by Admin announcements and product updates.",
    defaultSubject: "What’s new at Heyy Studio",
    defaultPreheader: "A new update from Heyy Studio.",
    defaultEyebrow: "Heyy Studio update",
    defaultTitle: "Something new is ready",
    defaultBody: "We’ve added something new to Heyy Studio. Open your workspace to see what changed and start exploring.",
    defaultCtaLabel: "Open Heyy Studio",
  },
  ...productionDefinitions(),
];

function productionDefinitions(): CommunicationTemplateDefinition[] {
  return [
    {
      key: "production.requested.client",
      name: "Production request received — client",
      category: "Production",
      description: "Confirmation sent when a client submits an expert-production request.",
      defaultSubject: "We received your production request",
      defaultPreheader: "Your production request was received successfully.",
      defaultEyebrow: "Production request received",
      defaultTitle: "Your request is with the Heyy Studio team",
      defaultBody: "Your production request was received successfully. Our team will review the selected concept, project context and requested scope before preparing a clear quote.",
      defaultCtaLabel: "Open your dashboard",
    },
    {
      key: "production.requested.admin",
      name: "Production request received — admin",
      category: "Production",
      description: "Operational alert for a new production request.",
      defaultSubject: "New {{service}} request — {{project_name}}",
      defaultPreheader: "A client submitted a new production request for review.",
      defaultEyebrow: "New production request",
      defaultTitle: "A project is ready for review",
      defaultBody: "A client submitted a production request with the connected Studio context. Review the brief, generated outputs and notes before preparing the quote.",
      defaultCtaLabel: "Review request",
    },
    {
      key: "quote.ready.client",
      name: "Quote ready — client",
      category: "Production",
      description: "Sent when a production quote is ready for review.",
      defaultSubject: "Your {{service}} quote is ready",
      defaultPreheader: "Your Heyy Studio production quote is ready for review.",
      defaultEyebrow: "Quote ready",
      defaultTitle: "Review your production proposal",
      defaultBody: "Your Heyy Studio quote is ready. Open the project workspace to review the scope, price, delivery estimate and included revisions before continuing to payment.",
      defaultCtaLabel: "Review quote",
    },
    {
      key: "quote.ready.admin",
      name: "Quote sent — admin",
      category: "Production",
      description: "Operational confirmation that a quote was sent.",
      defaultSubject: "Quote sent — {{project_name}}",
      defaultPreheader: "The client can now review the production quote.",
      defaultEyebrow: "Quote sent",
      defaultTitle: "The client can now review the quote",
      defaultBody: "The quote was created and connected to the Studio request. The client has been notified and can review the proposal from their workspace.",
      defaultCtaLabel: "Open request",
    },
    {
      key: "quote.replied.client",
      name: "Quote reply — client",
      category: "Production",
      description: "Sent after Heyy Studio answers a quote question.",
      defaultSubject: "Heyy Studio replied to your {{service}} quote question",
      defaultPreheader: "A new reply to your quote question is waiting.",
      defaultEyebrow: "Quote question answered",
      defaultTitle: "A new reply is waiting in your workspace",
      defaultBody: "The Heyy Studio team answered your question about the production quote. Open the project workspace to review the reply and continue when you are ready.",
      defaultCtaLabel: "View quote conversation",
    },
    {
      key: "production.message.client.admin",
      name: "Client production message — admin",
      category: "Production",
      description: "Operational alert when a client sends a production message.",
      defaultSubject: "New client message — {{project_name}}",
      defaultPreheader: "A client sent a new production message.",
      defaultEyebrow: "Client message",
      defaultTitle: "A client sent a production message",
      defaultBody: "A new message was added to the paid production workspace. Open the job to reply and keep the conversation inside Heyy Studio.",
      defaultCtaLabel: "Reply in production",
    },
    {
      key: "production.message.studio.client",
      name: "Studio production message — client",
      category: "Production",
      description: "Sent when Heyy Studio replies inside production.",
      defaultSubject: "New production message for {{project_name}}",
      defaultPreheader: "A new message was added to your production workspace.",
      defaultEyebrow: "Production message",
      defaultTitle: "Heyy Studio sent you a message",
      defaultBody: "A new message was added to your production workspace. Open the project to read it, download any attached references and reply.",
      defaultCtaLabel: "Open conversation",
    },
    {
      key: "payment.received.client",
      name: "Production payment received — client",
      category: "Production",
      description: "Production-workspace confirmation after quote payment. The separate payment receipt email contains the invoice.",
      defaultSubject: "Payment received for {{service}}",
      defaultPreheader: "Your payment was confirmed and production can begin.",
      defaultEyebrow: "Payment confirmed",
      defaultTitle: "Your production job is now active",
      defaultBody: "Your payment was confirmed successfully. Heyy Studio has created the production job and the team can now begin working from the approved project context.",
      defaultCtaLabel: "Track production",
    },
    {
      key: "payment.received.admin",
      name: "Production payment received — admin",
      category: "Production",
      description: "Operational alert after production payment.",
      defaultSubject: "Payment received — {{project_name}}",
      defaultPreheader: "A paid production job is ready for the team.",
      defaultEyebrow: "Payment received",
      defaultTitle: "A paid production job is ready",
      defaultBody: "The quote payment was confirmed and the production job was created automatically. Open the job to review the complete brief and begin assignment.",
      defaultCtaLabel: "Open production job",
    },
    {
      key: "revision.requested.client",
      name: "Revision requested — client",
      category: "Production",
      description: "Confirmation after a client submits revision feedback.",
      defaultSubject: "Revision request received",
      defaultPreheader: "Your revision feedback has been sent to the team.",
      defaultEyebrow: "Revision request received",
      defaultTitle: "Your feedback has been sent to the team",
      defaultBody: "Your revision request is now attached to the production job. The Heyy Studio team will review the changes and update the workspace when revised files are ready.",
      defaultCtaLabel: "Open project",
    },
    {
      key: "revision.requested.admin",
      name: "Revision requested — admin",
      category: "Production",
      description: "Operational alert for new revision feedback.",
      defaultSubject: "Revision requested — {{project_name}}",
      defaultPreheader: "New client revision feedback needs review.",
      defaultEyebrow: "Revision requested",
      defaultTitle: "Client feedback needs review",
      defaultBody: "The client submitted a revision request. Review the requested changes against the approved scope and included revision allowance before responding.",
      defaultCtaLabel: "Open production job",
    },
    {
      key: "revision.ready.client",
      name: "Revision ready — client",
      category: "Production",
      description: "Sent when revised files are ready.",
      defaultSubject: "Your revision is ready for review",
      defaultPreheader: "Revised files are now available in your workspace.",
      defaultEyebrow: "Revision ready",
      defaultTitle: "Your revised files are available",
      defaultBody: "The Heyy Studio team uploaded revised files to your project. Open the workspace to compare, download, approve or request another revision.",
      defaultCtaLabel: "Review revision",
    },
    {
      key: "revision.approved.admin",
      name: "Revision approved — admin",
      category: "Production",
      description: "Operational confirmation that the client approved a revision.",
      defaultSubject: "Revision approved — {{project_name}}",
      defaultPreheader: "The client approved the latest production revision.",
      defaultEyebrow: "Client approval",
      defaultTitle: "The client approved the revision",
      defaultBody: "The latest revision was approved. Continue the production workflow or prepare final deliverables from the approved version.",
      defaultCtaLabel: "Open production job",
    },
    {
      key: "production.status.client",
      name: "Production status update — client",
      category: "Production",
      description: "Shared override for assigned, in-progress, review, deliverables-ready and completion updates.",
      defaultSubject: "Update on your {{service}}",
      defaultPreheader: "Your Heyy Studio production project has a new update.",
      defaultEyebrow: "Production update",
      defaultTitle: "Your project has a new update",
      defaultBody: "The production status changed. Open the project workspace to see the latest timeline, messages and next actions.",
      defaultCtaLabel: "Track production",
    },
  ];
}

export function communicationTemplateDefinition(key: string) {
  return COMMUNICATION_TEMPLATE_CATALOG.find((item) => item.key === key) || null;
}
